<?php
if (!defined('ABSPATH')) exit;

//主题外观设置
AYF::new_opt(array(
    'title' => '外观/布局设置',
    'parent' => 'theme',
    'slug' => 'layout',
    'desc' => 'AIYA-CMS 主题，外观样式、配色切换、页面布局和组件设置',
    'fields' => array(
        array(
            'desc' => '页面加载动画',
            'type' => 'title_2',
        ),
        array(
            'title' => '启用页面加载动画',
            'desc' => '首次打开页面时，使用加载动画层覆盖页面',
            'id' => 'site_loading_animation',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '页面加载动画',
            'desc' => '选择默认的 SVG 动画',
            'id' => 'site_page_default_selector',
            'type' => 'radio',
            'sub'  => array(
                'audio' => 'Audio',
                'bars' => 'Bars',
                'oval' => 'Oval',
                'puff' => 'Puff',
                'spinning-circles' => 'Spinning Circles',
                'tail-spin' => 'Tail Spin',
                'three-dots' => 'Three Fots',
                'custom' => '自定义',
            ),
            'default' => 'three-dots',
        ),
        array(
            'title' => '页面加载动画（自定义）',
            'desc' => '覆盖上一项设置，上传自定义的 SVG 或 GIF 动画',
            'id' => 'site_page_custom_selector',
            'type' => 'upload',
            'button_text' => '上传',
            'default'  => '',
        ),
        array(
            'desc' => '顶部导航（Topbar）',
            'type' => 'title_2',
        ),
        array(
            'title' => '顶部导航锁定',
            'desc' => '开关页面顶部导航栏悬浮锁定（跟随滚动）',
            'id' => 'site_header_sticky_top',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '顶部导航菜单',
            'desc' => '开关页面顶部导航菜单折叠显示',
            'id' => 'site_header_menu_drawer',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'desc' => '侧栏组件（Sitebar）',
            'type' => 'title_2',
        ),
        array(
            'title' => '禁用左侧菜单栏',
            'desc' => '不使用侧边栏菜单时，启用此项',
            'id' => 'site_aside_bar_type',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '左侧菜单宽度',
            'desc' => '设置侧边栏菜单宽度，默认为 <code>280px</code>',
            'id' => 'site_aside_bar_width',
            'type' => 'text',
            'default' => '280px',
        ),
        array(
            'desc' => '文章列表布局（主循环）',
            'type' => 'title_2',
        ),
        array(
            'title' => '列表循环结构',
            'desc' => '设置文章列表的输出模式，文章列表的输出数量请在站点中设置',
            'id' => 'site_loop_mode',
            'type' => 'radio',
            'sub'  => array(
                //'blog' => '博客（显示正文）',
                'list' => '列表（CMS模式）',
                'grid' => '卡片（CMS模式）',
                //'fall' => '瀑布流（Masonry模式）',
            ),
            'default' => 'grid',
        ),
        array(
            'title' => '显示最新文章标记',
            'desc' => '设置文章列表的标题显示，为当日发布的文章增加一个“最新”的徽章标记',
            'id' => 'site_loop_new_badge',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '显示日期为几天前',
            'desc' => '设置文章列表的日期显示，转换发布日期为 TIMEAGO 格式',
            'id' => 'site_loop_time_ago',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '列表宽度',
            'desc' => '设置列表宽度，仅影响卡片和瀑布流模式布局',
            'id' => 'site_loop_span',
            'type' => 'radio',
            'sub'  => array(
                '2' => '2列',
                '3' => '3列',
                '4' => '4列',
            ),
            'default' => '4',
        ),
        array(
            'title' => '分页设置',
            'desc' => '设置文章列表的分页选择器',
            'id' => 'site_loop_page',
            'type' => 'radio',
            'sub'  => array(
                'full' => '完整分页（显示上/下一页）',
                'page' => '简单分页（仅分页）',
                'more' => 'AJAX加载更多',
                'roll' => 'AJAX加载更多（自动）',
            ),
            'default' => 'full',
        ),
        array(
            'desc' => '配色设置（Color）',
            'type' => 'title_2',
        ),
        array(
            'title' => '自动配色',
            'desc' => '设置页面中主要组件的颜色，层叠样式自动匹配',
            'id' => 'site_color_element',
            'type' => 'color',
            'default' => '#0d6efd',
        ),
        array(
            'desc' => '手动配色参数需为完整的主题参数，请见主题文档',
            'type' => 'message',
        ),
        array(
            'title' => '手动配色',
            'desc' => '自定义方式设置所有组件配色',
            'id' => 'site_color_custom_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '自定义样式表',
            'desc' => '自定义方式设置所有组件配色',
            'id' => 'site_color_custom',
            'type' => 'code_editor',
            'settings' => array(
                'lineNumbers'   => true, 
                'tabSize'       => 2,
                'theme'         => 'monokai',
                'mode'          => 'css',
            ),
            'default' => aya_theme_head_css_custom_rule(1),
        ),
        array(
            'desc' => '夜间模式（DarkMode）',
            'type' => 'title_2',
        ),
        array(
            'title' => '默认开启暗色模式',
            'desc' => '默认页面配色为暗色模式',
            'id' => 'site_dark_mode_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'desc' => '页面背景（Background）',
            'type' => 'title_2',
        ),
        array(
            'title' => '页面背景色',
            'desc' => '设置页面中主要组件的颜色，层叠样式自动匹配',
            'id' => 'site_background_color',
            'type' => 'color',
            'default' => '#ededed',
        ),
        array(
            'title' => '启用背景图片',
            'desc' => '自定义方式设置所有组件配色',
            'id' => 'site_background_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '全局背景图片',
            'desc' => '上传页面背景图片，不需要背景图时此项留空即可',
            'id' => 'site_background_upload',
            'type' => 'upload',
            'button_text' => '上传',
            'default'  => AYA_URI . '/assets/image/bg-dp.png',
        ),
        array(
            'title' => '背景图平铺',
            'desc' => '开关页面背景图片自动拉伸（开启后自动铺满背景）',
            'id' => 'site_background_center',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '背景图遮罩',
            'desc' => '开关页面背景图片的遮罩层',
            'id' => 'site_background_after',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'desc' => '页面特效',
            'type' => 'title_2',
        ),
        array(
            'title' => '全局灰色特效',
            'desc' => '开关页面全局灰色特效',
            'id' => 'site_gray_mode_type',
            'type' => 'switch',
            'default' => false,
        ),
    ),
));
