<?php
if (!defined('ABSPATH')) exit;

//主题外观设置
AYF::new_opt(array(
    'title' => '布局设置',
    'parent' => 'theme',
    'slug' => 'layout',
    'desc' => 'AIYA-CMS 主题，页面布局和组件切换',
    'fields' => array(
        array(
            'desc' => '顶栏和侧栏组件（Sitebar）',
            'type' => 'title_2',
        ),
        array(
            'title' => '顶部导航锁定',
            'desc' => '开关页面顶部导航栏悬浮锁定',
            'id' => 'site_header_sticky_top',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '顶部导航菜单',
            'desc' => '开关页面顶部导航菜单折叠显示',
            'id' => 'site_header_menu_drawer',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'desc' => '侧栏组件（Sitebar）',
            'type' => 'title_2',
        ),
        array(
            'title' => '禁用左侧菜单栏',
            'desc' => '不使用侧边栏菜单时，启用此项',
            'id' => 'site_aside_bar_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '左侧菜单宽度',
            'desc' => '设置侧边栏菜单宽度，默认为 <code>280px</code>',
            'id' => 'site_aside_bar_width',
            'type' => 'text',
            'default' => '280px',
        ),
        array(
            'desc' => '横幅设置（Banner）',
            'type' => 'title_2',
        ),
        array(
            'title' => '横幅组件显示',
            'desc' => '开关Banner图片显示',
            'id' => 'site_banner_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '横幅文本',
            'desc' => '设置横幅显示的文本，设置为一言或自定义',
            'id' => 'site_banner_text_type',
            'type' => 'radio',
            'sub'  => array(
                'false' => '禁用',
                'hitokoto' => '一言',
                'custom' => '自定义',
            ),
            'default' => 'hitokoto',
        ),
        array(
            'title' => '横幅文本自定义',
            'desc' => '横幅标题的文本，仅设置为自定义时生效',
            'id' => 'site_banner_content',
            'type' => 'text',
            'default' => '',
        ),
        array(
            'title' => '横幅图片',
            'desc' => '上传页面横幅图片，建议宽度不低于1200px',
            'id' => 'site_banner_upload',
            'type' => 'upload',
            'button_text' => '上传',
            'default'  => AYA_URI . '/assets/image/banner-round.png',
        ),
        array(
            'title' => '横幅高度',
            'desc' => '横幅图片的高度，默认值为<code>360px</code>',
            'id' => 'site_banner_height',
            'type' => 'text',
            'default' => '360px',
        ),
        array(
            'desc' => '文章列表布局（主循环）',
            'type' => 'title_2',
        ),
        array(
            'title' => '列表循环结构',
            'desc' => '设置文章列表的输出模式，文章列表的输出数量请在站点中设置',
            'id' => 'site_loop_mode',
            'type' => 'radio',
            'sub'  => array(
                //'blog' => '博客（显示正文）',
                'list' => '列表（CMS模式）',
                'grid' => '卡片（CMS模式）',
                //'fall' => '瀑布流（Masonry模式）',
            ),
            'default' => 'grid',
        ),
        array(
            'title' => '显示最新文章标记',
            'desc' => '设置文章列表的标题显示，为当日发布的文章增加一个“最新”的徽章标记',
            'id' => 'site_loop_new_badge',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '显示日期为几天前',
            'desc' => '设置文章列表的日期显示，转换发布日期为 TIMEAGO 格式',
            'id' => 'site_loop_time_ago',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '列表宽度',
            'desc' => '设置列表宽度，仅影响卡片和瀑布流模式布局',
            'id' => 'site_loop_span',
            'type' => 'radio',
            'sub'  => array(
                '2' => '2列',
                '3' => '3列',
                '4' => '4列',
            ),
            'default' => '4',
        ),
        array(
            'title' => '分页设置',
            'desc' => '设置文章列表的分页选择器',
            'id' => 'site_loop_page',
            'type' => 'radio',
            'sub'  => array(
                'full' => '完整分页（显示上/下一页）',
                'page' => '简单分页（仅分页）',
                'more' => 'AJAX加载更多',
                'roll' => 'AJAX加载更多（自动）',
            ),
            'default' => 'full',
        ),
        array(
            'desc' => '文章页组件',
            'type' => 'title_2',
        ),
        array(
            'title' => '显示文章已过时提示',
            'desc' => '开关文章已过时提示，对已发布超过 30 天的文章显示已过时提示',
            'id' => 'site_single_outdated_tip',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '显示上/下一篇文章',
            'desc' => '开关上/下一篇文章导航组件',
            'id' => 'site_single_prev_next_post',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '显示作者卡片',
            'desc' => '开关作者卡片组件',
            'id' => 'site_single_author_panel',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '显示相关文章',
            'desc' => '开关相关文章组件，显示当前文章的5篇相关文章（根据标签和分类自动匹配）',
            'id' => 'site_single_related_posts',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '文尾声明信息',
            'desc' => '在文章末尾输出声明等额外文本',
            'id' => 'site_single_dis_claimer',
            'type' => 'textarea',
            'default' => '站点声明：本站部分内容转载自网络，作品版权归原作者及来源网站所有，任何内容转载、商业用途等均须联系原作者并注明来源。',
        ),
    ),
));
