<?php
if (!defined('ABSPATH')) exit;

//主题外观设置
AYF::new_opt(array(
    'title' => '正文页面',
    'parent' => 'theme',
    'slug' => 'format',
    'desc' => 'AIYA-CMS 主题，文章和页面正文格式过滤器',
    'fields' => array(
        array(
            'desc' => '正文样式设置',
            'type' => 'title_2',
        ),
        array(
            'title' => '正文文字颜色',
            'desc' => '设置正文文字的颜色，仅影响文内',
            'id' => 'site_main_color',
            'type' => 'color',
            'default' => '#222222',
        ),
        array(
            'title' => '正文文字大小',
            'desc' => '设置正文文字大小，仅影响文内，默认值<code>1rem</code>',
            'id' => 'site_main_size',
            'type' => 'text',
            'default' => '1rem',
        ),
        array(
            'title' => '正文文字行间距',
            'desc' => '设置正文文字行间距，仅影响文内，默认值<code>10px</code>',
            'id' => 'site_main_width',
            'type' => 'text',
            'default' => '10px',
        ),
        array(
            'desc' => '正文格式（过滤器）',
            'type' => 'title_2',
        ),
        array(
            'title' => '链接标签格式',
            'desc' => '给文章正文内部 &lt;a&gt; 标签自动添加 <code>rel="nofollow"</code> 和 <code>target="_blank"</code> 属性，仅对外部链接生效',
            'id' => 'site_content_link_filter',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '外部链接跳转设置',
            'desc' => '可选跳转方式，默认跳转方式为内链跳转',
            'id' => 'site_content_link_jump_page',
            'type' => 'radio',
            'sub'  => array(
                'false' => '直接跳转（不处理）',
                'go' => '内链跳转',
                'link' => '提示外部页面',
            ),
            'default' => 'go',
        ),
        array(
            'title' => '图片标签格式',
            'desc' => '文章正文内部 &lt;img&gt; 标签自动添加alt属性和懒加载属性',
            'id' => 'site_content_img_filter',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '标题标签格式',
            'desc' => '给文章正文内部 &lt;h1&gt; 、 &lt;h2&gt; 、 &lt;h3&gt; 标签自动添加锚点id（用于生成文章目录）',
            'id' => 'site_content_h1_filter',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '预定义标签格式',
            'desc' => '文章正文内部 &lt;pre&gt; 标签自动添加 heighlight 的样式',
            'id' => 'site_content_pre_filter',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '表格标签格式',
            'desc' => '给文章正文内部 &lt;table&gt; 表格添加 bootstrap 的样式',
            'id' => 'site_content_table_filter',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'desc' => '文章页组件',
            'type' => 'title_2',
        ),
        array(
            'title' => '显示作者卡片',
            'desc' => '开关作者卡片组件',
            'id' => 'site_single_author_panel',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '显示上/下一篇文章',
            'desc' => '开关上/下一篇文章导航组件',
            'id' => 'site_single_prev_next_post',
            'type' => 'switch',
            'default' => true,
        ),
        array(
            'title' => '已过时提示',
            'desc' => '开关文章已过时提示，对已发布超过 30 天的文章显示已过时提示',
            'id' => 'site_single_outdated_tip',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '文章声明信息',
            'desc' => '在文章末尾输出声明等额外文本',
            'id' => 'site_single_dis_claimer',
            'type' => 'textarea',
            'default' => '站点声明：本站部分内容转载自网络，作品版权归原作者及来源网站所有，任何内容转载、商业用途等均须联系原作者并注明来源。',
        ),
        array(
            'title' => '相关文章组件',
            'desc' => '开关相关文章组件，显示当前文章的5篇相关文章',
            'id' => 'site_single_related_posts',
            'type' => 'radio',
            'sub'  => array(
                'false' => '禁用',
                'cats' => '获取当前分类（分类下最新文章）',
                'auto' => '获取标签和分类 （匹配并随机排序文章）',
            ),
            'default' => 'false',
        ),
        array(
            'title' => '点赞功能组件',
            'desc' => '开关点赞功能组件，显示可用评分模式和点赞计数',
            'id' => 'site_single_click_like',
            'type' => 'radio',
            'sub'  => array(
                'false' => '禁用',
                'scoring' => '打分组件',
                'click' => '点赞组件',
            ),
            'default' => 'false',
        ),
        array(
            'desc' => '代码高亮',
            'type' => 'title_2',
        ),
        array(
            'title' => '启用 Highlight.js',
            'desc' => '设置是否加载代码高亮组件',
            'id' => 'site_highlight_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '设置 Highlight.js 样式',
            'desc' => '使用自定义的 Highlight.js 样式表，仅填写样式文件名，默认<code>atom-one-dark</code>',
            'id' => 'site_highlight_style',
            'type' => 'text',
            'default' => 'base16/atom-one-dark.css',
        ),
        array(
            'desc' => '排版纠正',
            'type' => 'title_2',
        ),
        array(
            'desc' => '*此功能使用 <code>jxlwqq/chinese-typesetting</code> 项目：<a href="https://github.com/jxlwqq/chinese-typesetting" target="_blank">查看文档</a>',
            'type' => 'message',
        ),
        array(
            'title' => '启用中文排版',
            'desc' => '在文章保存/更新时触发，执行统一排版纠正',
            'id' => 'site_save_post_chinese_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '启用的格式过滤器',
            'desc' => '接续上一项设置，选择需要启用的格式过滤器，详细说明请查阅相关项目文档',
            'id' => 'site_save_post_chinese_setting',
            'type' => 'checkbox',
            'sub'  => array(
                'insertSpace' => '中英文空格补正',
                'removeSpace' => '清除全角标点空格',
                'full2Half' => '全角转半角',
                'fixPunctuation' => '修复错误的标点符号',
                'properNoun' => '专有名词大小写',
                'removeClass' => '清除标签 Class 属性',
                'removeId' => '清除标签 ID 属性',
                'removeStyle' => '清除标签 Style 属性',
                'removeEmptyParagraph' => '清除空的段落标签',
                'removeEmptyTag' => '清除所有空的标签',
                'removeIndent' => '清除段首缩进',
            ),
            'default' => array('insertSpace', 'removeSpace', 'full2Half', 'fixPunctuation', 'properNoun'),
        ),
        array(
            'desc' => '文章别名',
            'type' => 'title_2',
        ),
        array(
            'desc' => '*此功能使用 <code>overtrue/pinyin</code> 项目',
            'type' => 'message',
        ),
        array(
            'title' => '使用拼音生成文章别名',
            'desc' => '在文章保存/更新时触发，如果未设置别名（为空时），则自动生成',
            'id' => 'site_save_post_slug_pinyin_type',
            'type' => 'switch',
            'default' => false,
        ),
        array(
            'title' => '使用拼音生成分类别名',
            'desc' => '在分类保存/更新时触发，如果未设置别名（为空时），则自动生成',
            'id' => 'site_save_term_slug_pinyin_type',
            'type' => 'switch',
            'default' => false,
        ),
    ),
));
